#' @importFrom methods new
#' @importFrom stats IQR
#' @importFrom stats na.omit
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats aov
#' @importFrom stats oneway.test
#' @importFrom stats p.adjust
#' @importFrom stats TukeyHSD
#' @importFrom data.table fread
#' @importFrom tidyr pivot_longer
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_density
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 labs
#' @importFrom limma normalizeQuantiles
#' @importFrom limma makeContrasts
#' @importFrom limma lmFit
#' @importFrom limma contrasts.fit
#' @importFrom limma eBayes
#' @importFrom limma topTable
#' @importFrom dplyr mutate
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom dplyr across
#' @importFrom dplyr do
#' @importFrom dplyr ungroup
#' @importFrom dplyr pull
#' @importFrom dplyr left_join
#' @importFrom dplyr ungroup
#' @importFrom utils head
#' @importFrom utils tail
#' @importFrom utils read.csv
#' @importFrom utils stack
#' @importFrom ggplot2 geom_segment
#' @importFrom grid arrow
#' @importFrom grid unit
#' @importFrom ggrepel geom_text_repel
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylim
#' @importFrom factoextra fviz_eig
#' @importFrom factoextra get_pca_var
#' @importFrom dplyr slice_max
#' @importFrom dplyr select
#' @importFrom stats prcomp
#' @importFrom dplyr filter
#' @importFrom rrcovNA impSeqRob
#' @importFrom rrcovNA impSeq
#' @importFrom DreamAI impute.RegImpute
#' @importFrom SeqKnn SeqKNN
#' @importFrom boot boot
#' @importFrom boot boot.ci
#' @importFrom harmony RunHarmony
#' @importFrom magrittr set_names
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_color_discrete
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 element_blank
#' @importFrom umap umap
#' @importFrom ggplot2 stat_ellipse
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ComplexHeatmap HeatmapAnnotation
#' @importFrom ComplexHeatmap Heatmap
#' @importFrom ConsensusClusterPlus ConsensusClusterPlus
#' @importFrom dplyr full_join
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 coord_fixed
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr separate
#' @importFrom dplyr arrange
#' @importFrom spdep cell2nb
#' @importFrom purrr map2_dbl
#' @importFrom purrr map_dbl
#' @importFrom purrr map
#' @importFrom purrr map2
#' @importFrom spdep nb2listw
#' @importFrom spdep nb2mat
#' @importFrom spdep joincount.multi
#' @importFrom purrr map_df
#' @importFrom ape Moran.I
#' @importFrom stats cor
#' @importFrom stats wilcox.test
#' @importFrom stats model.matrix
#' @importFrom grid gpar
#' @importFrom grDevices colorRampPalette
#' @importFrom tidyselect everything
#' @importFrom mixOmics plsda
#' @importFrom GSEABase GeneSet
#' @importFrom GSEABase GeneSetCollection
#' @importFrom GSEABase getGmt
#' @importFrom GSEABase geneIds
#' @importFrom clusterProfiler bitr
#' @importFrom dplyr where
#' @importFrom GSVA ssgseaParam
#' @importFrom GSVA gsva
#' @importFrom fgsea fgsea
#' @importFrom Mfuzz filter.std
#' @importFrom Mfuzz standardise
#' @importFrom Mfuzz mfuzz
#' @importFrom Mfuzz Dmin
#' @importFrom Mfuzz mestimate
#' @importFrom stats aggregate
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 element_line
#' @importFrom car leveneTest
#' @importFrom CIBERSORT cibersort
#' @importFrom jjPlot geom_jjPointPie
#' @import glmnet
#' @import Biobase
#' @import e1071
NULL
